name: one_pixel_game_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.8.1
  flame_audio: ^2.0.4
  flame_tiled: ^1.12.0

  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/bgm/
    - assets/audio/luffy/
    - assets/images/
    - assets/images/luffy/sprites/
    - assets/images/luffy/sprites/idle/
    - assets/images/luffy/sprites/jumping/
    - assets/images/luffy/sprites/running/
    - assets/tiles/

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
